rfc: snpguest first version
virtee/snpguest pull request #1
Opened 2023-04-18 14:59 UTC by DGonzalezVillal

Initial version of the snpguest utility tool. Can request report, extended report, certificate chain from kds and VCEK from kds. Can also verify root of trust.

2023-04-20 00:23 UTC, tylerfanelli requested changes
Thanks @DGonzalezVillal, I've left some comments.

Ultimately, I think this PR can hold off until we release the initial `virtee/snp` crate (whether that is included in the `virtee/sev` crate or by itself). This crate will allow these commands to be implemented much simpler, especially when concerning certificates.

2023-04-20 00:23 UTC, tylerfanelli commented on src/request.rs
> +        // Open sev firmware device
```suggestion
```

2023-04-20 00:23 UTC, tylerfanelli commented on src/request.rs
> +        // Create snp request structure
```suggestion
```

2023-04-20 00:23 UTC, tylerfanelli commented on src/request.rs
> +        // Request extended report
```suggestion
```

2023-04-20 00:23 UTC, tylerfanelli commented on src/request.rs
> +mod extended_report {
Instead of `get_report` and `get_extended_report`, can `get_report` just include a flag `--extended` to include the certs?

2023-04-24 12:48 UTC, larrydewey requested changes

2023-04-24 12:48 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    User needs to pass 64 bytes of data in any file format into request_file in order to be able to request the attestation report.
Although it isn't required, it is strongly suggested. The unique data from the user provides an additional means of verifying the report hasn't been tampered with. Perhaps if they don't specify one, we could create a pseudo-random buffer and print it out for the user to look for it in the report?

2023-04-24 12:48 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    User needs to pass 64 bytes of data in any file format into request_file in order to be able to request the attestation report.
Here, I believe the request file is the means of passing the 64-byte value. Depending on how we take the application, it *could* be required.

2023-04-24 12:48 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    The user should specify their host processory type using the processory_type flag, it will default to "Milan".
Agreed. It would be a good idea to have this a bit more dynamic.

2023-04-24 12:48 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    The user should specify their host processory type using the processory_type flag, it will default to "Milan".
+1

2023-04-24 12:48 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    If no path is provided for attestation report, the program will look for an attestation report in the local directory by default ("./attestation_report.bin").
This would be pretty helpful. I am trying to think through a scenario where a user may __not__ want this to occur. What is the VM / container is running in an isolated network?

2023-04-24 12:48 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    usage: snpguest verify-root-of-trust --ark_path $ARK_PATH --ask_path $ASK_PATH --vcek_path $vcek_path
True. I think this could be re-worded to verify certificate chain, or add in the report.

2023-04-24 12:48 UTC, larrydewey commented on src/request.rs
> +        pub vmpl: u32,
Technically the API doesn't required a value, so this can be an `Option`.

2023-04-24 12:48 UTC, larrydewey commented on src/request.rs
> +mod extended_report {
Seems reasonable enough to me.

2023-04-26 02:36 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    User needs to pass 64 bytes of data in any file format into request_file in order to be able to request the attestation report.
Yes, that can be a viable option.

2023-04-28 18:12 UTC, DGonzalezVillal commented on src/request.rs
> +        pub vmpl: u32,
Will make it option, will default to 1 if no value is provided

2023-05-05 18:42 UTC, larrydewey approved these changes

2023-05-12 19:38 UTC, DGonzalezVillal commented
Restructuring of the project has now been done in this latest command. I also addressed all the comments and the project is using the latest sev library. I know there are a couple of things that could be done in a quicker way (less code), but I also want to make sure I'm outputting as much information as possible to the user.

2023-05-18 19:10 UTC, tylerfanelli requested changes
Thanks @DGonzalezVillal , overall looks really good.

In a lot of these commands, we're relying on serialized files for attestation reports to be passed. In my opinion this isn't necessary, since we have access to `/dev/sev-guest` and can fetch it from the PSP ourselves. Why not just fetch the report when we can?

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch ca [-p,--processor] $PROCESSOR_TYPE [-c, --certs] $CERTS_PATH
```suggestion
    usage: snpguest fetch ca $PROCESSOR_TYPE $CERTS_PATH
```

Usually, with flags such as `-p, --processor` and `-c, --certs` it indicates that they are optional. In this command, they are not. We can remove these.

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    The user must specify their host processor type using the --processor flag.
```suggestion
    The user must specify their host processor type.
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch vcek [-p, --processor] $PROCESSOR_TYPE [-c, --certs] $CERTS_PATH  [-a, --att-report] $ATTESTATION_REPORT_PATH
```suggestion
    usage: snpguest fetch vcek $PROCESSOR_TYPE $CERTS_PATH
```

Same here, remove the flag indicators. Also, why not just request the attestation report from the PSP?

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    If no path is provided for the attestation report, the program will look for an attestation report in the local directory by default ("./attestation_report.bin").
```suggestion
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +*snpguest guest verify certificate-chain*::
```suggestion
*snpguest guest verify certs*::
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest verify certificate-chain [-c, --certs] $CERTS_PATH
```suggestion
    usage: snpguest verify certs $CERTS_PATH
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    If no path is provided for the certificates, the program will look for them in the local cert directory ("./certs")
Make the path required, instead of searching `./certs`?

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest verify tcb [-c, --certs] $CERTS_PATH [-a, --att-report] $ATTESTATION_REPORT_PATH
```suggestion
    usage: snpguest verify tcb $VCEK
```

It's only the VCEK we're looking for here, so just give that file. Also fetch the attestation report from the PSP?

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    The user needs to provide a path to the attestation report and to the directory where the VCEK certificate is stored.
```suggestion
    The user needs to provide a path to the VCEK certificate.
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    If no path is provided for the attestation report, the program will look for it in the local directory ("./attestation_report.bin").
```suggestion
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    If no path is provided for the certificate, the program will look for it in the local cert directory ("./certs").
```suggestion
```

Just require it altogether.

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +*snpguest verify attestation-signature*::
```suggestion
*snpguest verify signature*::
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest verify attestation-signature [-c, --certs] $CERTS_PATH [-a, --att-report] $ATTESTATION_REPORT_PATH
```suggestion
    usage: snpguest verify signature $CERTS_PATH
```

Fetch the attestation report

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    If no path is provided for the certificate, the program will look for it in the local cert directory ("./certs").
```suggestion
```

2023-05-18 19:10 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest display report [-a, --att-report] $ATTESTATION_REPORT_PATH
Fetch the report?

2023-05-19 15:13 UTC, larrydewey commented on Cargo.toml
> +sev = { git = "https://github.com/virtee/sev", branch = "main", features = ['openssl']}
+1 for this

2023-05-19 15:13 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    The user can use the --random flag to generate a request-file with randomly generated 64 byts. If the user provides a request path and uses the --random flag, the data will be written into the pr
+1 For this

2023-05-19 20:04 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch ca [-p,--processor] $PROCESSOR_TYPE [-c, --certs] $CERTS_PATH
I understand. I removed the processor type flag. Shouldn't certs be optional if I have a default directory where the program looks for certs? It currently looks for the certs in "./certs" if no path is provided.

2023-05-19 20:09 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch ca [-p,--processor] $PROCESSOR_TYPE [-c, --certs] $CERTS_PATH
@DGonzalezVillal You can require it altogether

2023-05-19 20:15 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch ca [-p,--processor] $PROCESSOR_TYPE [-c, --certs] $CERTS_PATH
@tylerfanelli understood. If the provided directory already exists do we want to create an error or create it for them?

2023-05-19 20:18 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch ca [-p,--processor] $PROCESSOR_TYPE [-c, --certs] $CERTS_PATH
@DGonzalezVillal 

If directory exists already ---> use it and overwrite any cert files.
If directory doesn't exist already ---> create it and fill it with the certs

Sounds like this would be a nice way to do things?

2023-05-22 13:53 UTC, tylerfanelli approved these changes
Nice work! We can cut a release now.

2023-05-22 13:54 UTC, merged

2023-05-23 20:10 UTC, dubek commented on src/certs/mod.rs
> +    ];
maybe clearer:

```rust
const PEM_START: &[u8] = b"-----BEGIN CERTIFICATE-----";
```

(I think this is identical.)