Report
virtee/snpguest pull request #10
Opened 2023-06-09 19:21 UTC by DGonzalezVillal

Made it so that whenever an attestation report is being used, for either verification or request, if no report is provided, the program will request one with random data and default parameter values to use. The report won't be stored. To store a report for use, then the snpguest report command has to be used. Added a new fetch command to pull the entire cert chain at once. The cert chain can be pulled from the kds or the host extended report memory using this command. Also some fixes to make commands match throughout the program

2023-06-12 11:46 UTC, larrydewey requested changes
There are a few things you could adjust here. Let me know if you have any questions.

2023-06-12 11:46 UTC, larrydewey commented on src/fetch.rs
> +                    }
It seems like we are repeating this quite a bit. Maybe we break this out into a private function?

2023-06-13 19:03 UTC, larrydewey approved these changes
LGTM

2023-07-05 17:13 UTC, larrydewey commented
@DGonzalezVillal looks like your fork is out-of-sync. Rebase, and we can get this rolling.

2023-07-10 21:08 UTC, DGonzalezVillal commented
@tylerfanelli Does this look good to merge?

2023-07-11 04:56 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest report [-e, --extended-report] [-r, --random] [-v, --vmpl] $VMPL [-d, --request-data] $REQUEST_FILE [-a, --att-report] $ATT_REPORT_PATH $CERTS_PATH
I still think that `report` should be a standalone command for the report (i.e. leave the `--extended-report` option out, and leave that to the `certs` command)

2023-07-11 05:01 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest report [-e, --extended-report] [-r, --random] [-v, --vmpl] $VMPL [-d, --request-data] $REQUEST_FILE [-a, --att-report] $ATT_REPORT_PATH $CERTS_PATH
Also, with something like `[-v, --vmpl] $VMPL`, it usually indicates that the argument is optional. In this case, it is not, so there is no need to include these flags.
```suggestion
    usage: snpguest report [-r, --random] $VMPL $REQUEST_FILE $ATT_REPORT_PATH
```

2023-07-11 05:02 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    Both certificates will be written in ".pem" format.
Should PEM be required? We could include the encoding format as a command line argument.

2023-07-11 05:04 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch vcek $CERTS_DIR $PROCESSOR_MODEL [-a, --att-report] $ATT_REPORT_PATH
We should probably just force the user to enter the attestation report file instead of defaulting to `./attestation_report.bin`
```suggestion
    usage: snpguest fetch vcek $CERTS_DIR $PROCESSOR_MODEL $ATT_REPORT_PATH
```

2023-07-11 05:05 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch certs [-e, --extended-report] $CERTS_DIR $PROCESSOR_MODEL [-a, --att-report] $ATT_REPORT_PATH
Is this command needed? It's replaceable with the `fetch ca` and `fetch vcek` commands.

2023-07-11 05:06 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest verify tcb $CERTS_DIR [-a, --att-report] $ATT_REPORT_PATH
We should probably just require the user to give the report path.
```suggestion
    usage: snpguest verify tcb $CERTS_DIR $ATT_REPORT_PATH
```

2023-07-11 05:08 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest verify signature $CERTS_DIR [-a, --att-report] $ATT_REPORT_PATH
Why not merge `verify tcb` and `verify signature` into one command? They take the same arguments.

Also, we should require the user to give the attestation report path
```suggestion
    usage: snpguest verify signature $CERTS_DIR $ATT_REPORT_PATH
```

2023-07-11 05:08 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest display report [-a, --att-report] $ATT_REPORT_PATH
Require user to give report path
```suggestion
    usage: snpguest display report $ATT_REPORT_PATH
```

2023-07-11 05:14 UTC, tylerfanelli requested changes
Apologies for the delay. I left some comments.

2023-07-11 17:03 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest report [-e, --extended-report] [-r, --random] [-v, --vmpl] $VMPL [-d, --request-data] $REQUEST_FILE [-a, --att-report] $ATT_REPORT_PATH $CERTS_PATH
The reason I kept extended-report is to keep parity with the actual IOCTL call. I guess it is not really needed, but it's also nice to have one command that will get everything done in one step (Pulling both the report and the certificates at once). What if we remove the flag and add another command call extended-report? So, snpguest extended-report?
Most people will probably use VMPL 1, that's why it defaults to that. Should we make it a mandatory parameter? 
@larrydewey thoughts on this?

2023-07-11 17:08 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    Both certificates will be written in ".pem" format.
The reason it defaults to PEM is because the certificates already come in PEM format from the KDS and I was keeping it simple. But it doesn't hurt to add the option for the user to pick. Do you think this should be an optional parameter, or make the user pick one or the other?

2023-07-11 17:10 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch vcek $CERTS_DIR $PROCESSOR_MODEL [-a, --att-report] $ATT_REPORT_PATH
So, in this new workflow if the user does not provide an attestation report file, then the program will automatically fetch a new one for them. That way the user doesn't need to be constantly be providing one. Would you prefer if I add a flag that says get a new att-report to fetch the vcek and if the flag is not provided, then make the user provide an Attestation Report?

2023-07-11 17:23 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch certs [-e, --extended-report] $CERTS_DIR $PROCESSOR_MODEL [-a, --att-report] $ATT_REPORT_PATH
The point of this command was to fetch the certificates from the host memory (i.e. extended report) and then I thought we might as well add the functionality to get all the certificates at once from the KDS. If it's to convoluted I don't mind reducing it to host certificates only.

2023-07-11 17:23 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest verify tcb $CERTS_DIR [-a, --att-report] $ATT_REPORT_PATH
see vcek comment

2023-07-11 17:23 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest display report [-a, --att-report] $ATT_REPORT_PATH
see snpguest fetch vcek comment

2023-07-11 17:24 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest verify signature $CERTS_DIR [-a, --att-report] $ATT_REPORT_PATH
I thought about this too. Would there be a situation were a user might want them as 2 different steps @larrydewey? If not, I don't mind merging them.

2023-07-11 17:35 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest report [-e, --extended-report] [-r, --random] [-v, --vmpl] $VMPL [-d, --request-data] $REQUEST_FILE [-a, --att-report] $ATT_REPORT_PATH $CERTS_PATH
> The reason I kept extended-report is to keep parity with the actual IOCTL call. I guess it is not really needed, but it's also nice to have one command that will get everything done in one step (Pulling both the report and the certificates at once).

It makes it a bit more complicated, as we're starting to duplicate functionality in commands. Users can get confused when multiple commands can do similar things.

> What if we remove the flag and add another command call extended-report? So, snpguest extended-report? Most people will probably use VMPL 1, that's why it defaults to that. Should we make it a mandatory parameter? @larrydewey thoughts on this?

For what reason? We have commands that do this functionality already.

2023-07-11 17:35 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    Both certificates will be written in ".pem" format.
Require the user to specify for clarity.

2023-07-11 17:36 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    Both certificates will be written in ".pem" format.
I think we should require the user to pick one for clarity.

2023-07-11 17:39 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch vcek $CERTS_DIR $PROCESSOR_MODEL [-a, --att-report] $ATT_REPORT_PATH
We have the `report` command to fetch the attestation report. So this command should expect one that a user can easily generate beforehand:

```
snpguest report ./attestation_report.bin
snpguest fetch vcek ./certs milan ./attestation_report.bin
```

2023-07-11 17:40 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest fetch certs [-e, --extended-report] $CERTS_DIR $PROCESSOR_MODEL [-a, --att-report] $ATT_REPORT_PATH
I would remove the KDS part then. That also duplicates functionality within commands.

2023-07-11 17:42 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    usage: snpguest verify signature $CERTS_DIR [-a, --att-report] $ATT_REPORT_PATH
If need be, you can do:
`snpguest verify` for both
`snpguest verify tcb` for tcb
`snpguest verify signature` for signature

but its still just one command, not two separate ones

2023-07-11 22:00 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    Both certificates will be written in ".pem" format.
I shouldn't be too much work to wrap/unwrap the certificates in PEM/DER format respectively. Generally this is as simple as a function call.

2023-07-11 22:04 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    usage: snpguest verify signature $CERTS_DIR [-a, --att-report] $ATT_REPORT_PATH
I think we would be good to merge them. I can't think of a reason why we might want to check the TCB separately unless perhaps the report was generated with a revoked certificate?

2023-07-19 19:59 UTC, DGonzalezVillal commented
@tylerfanelli and @larrydewey, made the changes we talked about in the meeting. Please re-review and lmk if there are any other changes you would like.

2023-07-20 22:01 UTC, larrydewey approved these changes
I think this is where we discuss having it. LGTM

2023-07-21 00:39 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +    The attestation report will be ingored for this request, to request and store an attestation report use the "report" command.
We can remove this line. It's a bit confusing. Users aren't aware that a report is fetched in the background via `EXT_REPORT`

2023-07-21 00:45 UTC, tylerfanelli approved these changes
Approved, but please do not release `0.3.0` yet, as there's some slight changes I'd like to make.

2023-07-21 00:48 UTC, tylerfanelli commented
CC @larrydewey 

"_This branch cannot be rebased due to conflicts_"

Do you see what these conflicts are? I'm not aware of any.

2023-07-21 02:18 UTC, tylerfanelli approved these changes

2023-07-21 22:21 UTC, larrydewey commented
CC @tylerfanelli I am not seeing an error?

![image](https://github.com/virtee/snpguest/assets/41640198/ba62c3b4-a631-4b48-9d80-330a92dfb611)

2023-07-24 16:21 UTC, tylerfanelli commented
@DGonzalezVillal There are a number of problems when running `cargo clippy`. Can you address them?

2023-07-24 20:10 UTC, merged