Azure detection + attestation report fetch
virtee/snpguest pull request #16
Opened 2023-07-25 05:10 UTC by tylerfanelli

This PR introduces two new features:
1. Detecting if snpguest is running inside of a Azure CVM
2. If so, fetching the attestation report from the vTPM, rather than the /dev/sev-guest device

2023-07-25 05:24 UTC, tylerfanelli commented
Closes #5

2023-07-25 05:25 UTC, tylerfanelli commented
CC @berrange

2023-07-25 07:49 UTC, berrange commented on src/hyperv/mod.rs
> +    let cpuid = unsafe { __cpuid(CPUID_HYPERV_VENDOR_AND_MAX_FUNCTIONS) };
Since there's no previous `_cpuid` call made that validates it, it would be best practice to first check `__cpuid(CPUID_GET_HIGHEST_FUNCTION) `and check  `eax >= CPUID_HYPERV_VNEDOR_AND_MAX_FUNCTIONS`.

It also ought to check `__cpuid(CPUID_PROCESSOR_INFO_AND_FEATURE_BIT)` and check `ecx & CPUID_FEATURE_HYPERVISOR` to validate we are in a VM too.

http://git.annexia.org/?p=virt-what.git;a=blob;f=virt-what-cvm.c;

2023-07-25 07:57 UTC, berrange commented on src/report.rs
> +        hyperv::report::get()?
For `args.vmpl` we need to mandate that it is `0`, because the Azure HCL report is created at VMPL 0

I'm not sure what todo for `args.random` - we can't honour the current semantics for either `true` or `false` value - the data won't be random, and the user also can't provide their own data. Basically the report data is fixed at what HCL added, which is the TPM attestation key.  We should however still write out the fixed HCL report data to `args.request_file` I think

2023-07-25 17:22 UTC, tylerfanelli commented on src/hyperv/mod.rs
> +    let cpuid = unsafe { __cpuid(CPUID_HYPERV_VENDOR_AND_MAX_FUNCTIONS) };
Sure, fixed in https://github.com/virtee/snpguest/pull/16/commits/b8983b42f1edb47ab6a16f0747fe0e86c2a3c5f3

2023-07-25 17:28 UTC, tylerfanelli commented on src/report.rs
> +        hyperv::report::get()?
So, we can fail if **VMPL > 1 && Hyper-V report is detected**. Should the command fail if `args.request_file` is given with a message `Hyper-V request data is fixed and cannot be changed, do not submit a request file as input`? The same could be said with `args.random`. Maybe these args should be re-considered for the command if so.

2023-07-25 17:50 UTC, berrange commented on src/report.rs
> +        hyperv::report::get()?
Essentially we have three scenarios

 * User provides a request file as input
 * User requests random data as input
 * Input is pre-determined by platform

We could add a third argument `--platform` which is mutually exclusive with `--random`

* `--request-data` - user provided input, unchanged on output
* `--random` - auto-generated input, output `./random-request-file.txt`
*` --random`, `--request-data PATH` - auto-generated input, output `$PATH`
* `--platform` - pre-determined input, output `./platform-request-file.txt`
* `--platform`, `--request-data PATH` - pre-detrermined input, output `$PATH`

2023-07-25 19:50 UTC, larrydewey approved these changes

2023-07-27 04:24 UTC, tylerfanelli commented on src/report.rs
> +        hyperv::report::get()?
In https://github.com/virtee/snpguest/pull/16/commits/0c80f34376cf5aca4ec53c6d1f983441cfe28fd9 I removed the `--random` flag altogether. The user is instead required to give a "request file" as an argument.

- For regular guests, the data in the request data file will be used as the data in the attestation report.
- For Hyper-V guests, the platform data already present in the report is written to the request file.

Although a bit unavoidable here, I don't like the `request-file` arg being interpreted differently based on what platform you're running on. What do you think?

2023-07-27 20:43 UTC, larrydewey approved these changes
CC @DGonzalezVillal Just a heads up on the API changes made here.

2023-07-27 20:57 UTC, DGonzalezVillal reviewed
I just have a couple of questions/comments on the workflow, and the certificates command. Everything else looks good

2023-07-27 20:57 UTC, DGonzalezVillal commented on src/main.rs
> +    let hv = hyperv::present();
Do we want to check for Hyper-V every single time the tool is used? Why wouldn't we just check whenever people request a report?

2023-07-27 20:57 UTC, DGonzalezVillal commented on src/main.rs
>          SnpGuestCmd::Certificates(args) => certs::get_ext_certs(args),
This command uses the get_extended_report command? Shouldn't there also be a hyper-v check for this function? It's essentially also requesting an attestation report, but also the certificates in memory. It's using the sev-guest firmware. Unless hyper-v doesn't have support for extended reports.

2023-07-27 20:57 UTC, DGonzalezVillal commented on src/certs.rs
>      let mut sev_fw: Firmware = Firmware::open().context("failed to open SEV firmware device.")?;
This command connects to the guest firmware. Would this work on hyper-v?

2023-07-27 22:03 UTC, tylerfanelli commented on src/main.rs
> +    let hv = hyperv::present();
There will be parity with other commands.

2023-07-27 22:03 UTC, tylerfanelli commented on src/main.rs
>          SnpGuestCmd::Certificates(args) => certs::get_ext_certs(args),
There is no `ext_report` available in hyper-v.

2023-07-27 22:05 UTC, tylerfanelli commented on src/certs.rs
>      let mut sev_fw: Firmware = Firmware::open().context("failed to open SEV firmware device.")?;
No, certs in Hyper-V come from the network AFAIK.

2023-07-28 11:16 UTC, berrange commented on src/report.rs
> +        hyperv::report::get()?
> In https://github.com/virtee/snpguest/commit/0c80f34376cf5aca4ec53c6d1f983441cfe28fd9 I removed the --random flag altogether. The user is instead required to give a "request file" as an argument.

Being able to omit the request file and just have the tool create a random nonce was desirable behaviour IMHO

> Although a bit unavoidable here, I don't like the request-file arg being interpreted differently based on what platform you're running on. What do you think?

I think it is highly undesirable, because the behaviour is not discoverable / reportable. 

With the 5 scenarios I illustrated above, each combination of args has clearly defined platform independent semantics. The command will either complete with the documented semantics, or an error will be reported if the platform can't honour that particular combination of args.

2023-07-28 15:10 UTC, DGonzalezVillal commented on src/report.rs
> +        hyperv::report::get()?
I second @berrange comment

2023-07-28 15:32 UTC, larrydewey commented on src/report.rs
> +        hyperv::report::get()?
> In [0c80f34](https://github.com/virtee/snpguest/commit/0c80f34376cf5aca4ec53c6d1f983441cfe28fd9) I removed the `--random` flag altogether. The user is instead required to give a "request file" as an argument.
> 
> * For regular guests, the data in the request data file will be used as the data in the attestation report.
> * For Hyper-V guests, the platform data already present in the report is written to the request file.
> 
> Although a bit unavoidable here, I don't like the `request-file` arg being interpreted differently based on what platform you're running on. What do you think?

@tylerfanelli was there a reason we wanted to remove this option? I must have missed this from my quick review. I agree with @berrange, this is a nice feature for users who care less about generating the request data, and just want to attest the report.

2023-07-28 15:34 UTC, larrydewey requested changes
Revoking approval until discussion is complete.

2023-07-28 16:00 UTC, larrydewey commented on src/main.rs
> +    let hv = hyperv::present();
I agree, I think it would make more sense to only check for Hyper-V when we are potentially going to interact with the PSP. All other functionality from the tool does not rely on architecture. The only other location I could potentially think this check would be useful is for enabling/disabling `--random`, as Hyper-V disallows the use of this flag.

2023-07-28 19:34 UTC, tylerfanelli commented on src/report.rs
> +        hyperv::report::get()?
@larrydewey The motivation to remove `--random` was to "clean up" the arguments of this command and try to give some uniformity, so that the experience was the same regardless if one was running on Azure or not. Corner cases such as 
- `--random` and `--platform` are mutually exclusive
- `--random` must fail on Azure
- `--platform` must fail on non-Azure
And the option inclusion of `--request-file`. I don't want to confuse users on the different flags and why/how they are used. If `--random` is desirable however, I'll change this to use `--platform`, and document it's prospective use cases (i.e. in Azure)

2023-07-28 19:36 UTC, tylerfanelli commented on src/main.rs
> +    let hv = hyperv::present();
An example I currently see is certs. In non-Azure, certs are fetched from the KDS. However, in Azure they are fetched from another MS-defined endpoint.

2023-08-01 03:05 UTC, tylerfanelli commented on src/report.rs
> +        hyperv::report::get()?
I removed the commit and added the `--platform` flag. To try and complicate things less, a user is required to input the name of a file to write the request data, rather than defaulting to `{random, platform}-request-data.txt`. Is this a desirable feature?

2023-08-04 19:22 UTC, larrydewey approved these changes
LGTM

2023-08-04 19:22 UTC, larrydewey commented on src/hyperv/mod.rs
> +    let cpuid = unsafe { __cpuid(CPUID_PROCESSOR_INFO_AND_FEATURE_BITS) };
Where we are using this again on line 29, would it make sense to have this mutable instead of re-creating the variable each time?
```suggestion
    let mut cpuid = unsafe { __cpuid(CPUID_PROCESSOR_INFO_AND_FEATURE_BITS) };
```

2023-08-04 19:23 UTC, larrydewey commented on src/hyperv/mod.rs
> +    let cpuid = unsafe { __cpuid(CPUID_PROCESSOR_INFO_AND_FEATURE_BITS) };
(not required, just a thought)

2023-08-04 19:23 UTC, larrydewey commented on src/main.rs
> +    let hv = hyperv::present();
Makes sense

2023-08-07 00:03 UTC, tylerfanelli commented on src/hyperv/mod.rs
> +    let cpuid = unsafe { __cpuid(CPUID_PROCESSOR_INFO_AND_FEATURE_BITS) };
Fixed in 49a6f10

2023-08-07 18:54 UTC, DGonzalezVillal approved these changes
LGTM

2023-08-08 00:28 UTC, merged