RFC Adding Derived Key Feature
virtee/snpguest pull request #21
Opened 2023-08-10 19:40 UTC by AdithyaKrishnan

Adding Derived Key Feature and ability to display derived key in Hex format.
Reopened due to conflicting commits.

2023-08-10 20:20 UTC, tylerfanelli commented
@AdithyaKrishnan Can you add a `Signed-off-by` line to the commit?

2023-08-14 19:37 UTC, DGonzalezVillal requested changes
Just some thoughts on documentation and general cleanliness to help users understand how to use this new feature.

2023-08-14 19:37 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    usage: snpguest key $KEY_PATH $ROOT_KEY_SELECT
```
usage: snpguest key $KEY_PATH $ROOT_KEY_SELECT
```
The flags are missing, look at other commands to see how to include those.

2023-08-14 19:37 UTC, DGonzalezVillal commented on src/display.rs
> +                keydata.push_str(&format!("{byte:02x} "));
I'd maybe add a small comment to explain how the terminal printing is being done.

2023-08-14 19:37 UTC, DGonzalezVillal commented on src/display.rs
> +        #[structopt(help = "Path to display key.")]
```suggestion
        #[structopt(help = "Path to key to display.")]
```

2023-08-14 19:37 UTC, DGonzalezVillal commented on src/key.rs
> +    #[structopt(help = "This is the directory where the derived key will be saved")]
```suggestion
    #[structopt(help = "This is the path where the derived key will be saved")]
```

2023-08-14 19:37 UTC, DGonzalezVillal commented on src/key.rs
> +        help = "This is the root key from which to derive the key. Input either VCEK or VMRK. VLEK is not supported yet."
No need to include VLEK comment

2023-08-14 19:37 UTC, DGonzalezVillal commented on src/key.rs
> +    pub rks: String,
I'd prefer slightly more descriptive variable name. Especially since when you run the --help command on terminal, the argument will appear as  the name of the variable. rks isn't very descriptive, root_key_select would help user's out more.

2023-08-14 19:37 UTC, DGonzalezVillal commented on src/key.rs
> +        help = "Specify which Guest Field Select bits to enable. Value of N for Guest Policy:0, Image ID:1, Family ID:2, Measurement:3, SVN:4, TCB Version:5 where Guest Field Select bit = 10^N"
The help is a little confusing. You're picking what data to mix into the derived key in the form of a binary number. It's not incorrect, I'm just trying to look at it as someone really new to this. Could you maybe re-word this?

2023-08-14 19:37 UTC, DGonzalezVillal commented on src/key.rs
The code looks good, I would also maybe add a comment or two in the code just to help people understand what is going on.

2023-08-15 02:50 UTC, tylerfanelli commented on docs/snpguest.1.adoc
> +                                      Select bit = 10^N
+1

2023-08-16 16:20 UTC, larrydewey requested changes

2023-08-16 16:20 UTC, larrydewey commented on src/display.rs
> +            for (i, byte) in key_report.iter().enumerate() {
It would probably make sense to just import `sev::util::hexdump()` to perform this action.

2023-08-16 16:56 UTC, AdithyaKrishnan commented on .gitignore
> +.gitignore
@DGonzalezVillal Had asked me to include it here. Don't mind removing it.

2023-08-16 16:57 UTC, AdithyaKrishnan commented on src/display.rs
> +use std::{path::PathBuf, str};
Removed

2023-08-16 16:59 UTC, AdithyaKrishnan commented on src/display.rs
> +            for (i, byte) in key_report.iter().enumerate() {
Copied and pasted this from existing util code. Can modify if needed.

2023-08-18 16:03 UTC, AdithyaKrishnan commented on src/display.rs
> +            for (i, byte) in key_report.iter().enumerate() {
Made the changes and while testing found it to be a private function. Hence reverting back to the original code

2023-08-18 21:28 UTC, larrydewey approved these changes

2023-08-18 21:32 UTC, larrydewey approved these changes

2023-08-18 21:40 UTC, DGonzalezVillal commented on docs/snpguest.1.adoc
> +    example: snpguest key $KEY_PATH $ROOT_KEY_SELECT --guest_field_select 100001 (Denotes Guest Policy:On, Image ID:Off, Family ID:Off, Measurement:Off, SVN:Off, TCB Version:On)
```suggestion
    The least significant (rightmost) bit is Guest Policy followed by Image ID, Family ID, Measurement, SVN, TCB Version which is the most significant (leftmost) bit. 
     example: snpguest key $KEY_PATH $ROOT_KEY_SELECT --guest_field_select 100001 (Denotes Guest Policy:On, Image ID:Off, Family ID:Off, Measurement:Off, SVN:Off, TCB Version:On)
    The --guest_svn specifies the guest SVN to mix into the key. Must not exceed the guest SVN provided at launch in the ID block.
    The --tcb_version specified the TCB version to mix into the derived key. Must not exceed CommittedTcb.
```

Since the example is referring to the --guest_field_select put the example under the corresponding flag.

2023-08-18 21:43 UTC, larrydewey approved these changes

2023-08-18 21:43 UTC, DGonzalezVillal approved these changes

2023-08-18 21:44 UTC, merged