Update Readme
virtee/snpguest pull request #28
Opened 2023-09-20 15:48 UTC by AdithyaKrishnan

2023-09-20 20:07 UTC, DGonzalezVillal requested changes

2023-09-20 20:07 UTC, DGonzalezVillal commented on README.md
> +- Several helper functions are defined within the modules to facilitate various tasks, including locating certificates in a directory, comparing certificate values, and verifying attestation report s
Although this is a good summary of how the code works and I appreciate the effort, I don't think this is needed in the README. The README should focus on how to use the tool, not so much on how it works. Unless you disagree @larrydewey @tylerfanelli

2023-09-20 20:07 UTC, DGonzalezVillal commented on README.md
> +# SNP Examples
Your examples are just a repeat from what you have above in commands. I would maybe use this section to show how would you go about going through a regular attestation workflow and an extended attestation workflow. This in addition to the flowcharts you added at the bottom would be very helpful.

2023-09-20 20:07 UTC, DGonzalezVillal commented on README.md
> +![alt text](https://github.com/virtee/snpguest/blob/main/docs/regular.png?raw=true)
I'm not sure if this is how you attach images. At least for me, in you repository, I can't see the images in the README.

2023-09-20 20:07 UTC, DGonzalezVillal commented on README.md
In addition to the other comments I left, I would also add a section on how to compile the tool. You also fail to mention the whole hyper-v section.

2023-09-20 21:23 UTC, larrydewey requested changes

2023-09-20 21:23 UTC, larrydewey commented on README.md
> +- It defines a structure for managing certificate paths (`CertPaths`) and functions for obtaining extended certificates from the AMD PSP.
```suggestion
- It defines a structure for managing certificate paths (`CertPaths`) and functions for obtaining extended certificates from the AMD Secure Processor.
```

2023-09-20 21:23 UTC, larrydewey commented on README.md
> +- It contains subcommands for fetching various types of certificates from the AMD PSP.
```suggestion
- It contains subcommands for fetching various types of certificates from the AMD Secure Processor.
```

2023-09-20 21:23 UTC, larrydewey commented on README.md
> +- It contains subcommands for displaying attestation reports and derived keys.
I think it would be beneficial to actually list out each sub-command, and what they are expected to do and how they are expected to be used.

2023-09-20 21:23 UTC, larrydewey commented on README.md
> +- It contains subcommands for displaying attestation reports and derived keys.
I think it would be beneficial to actually list out each sub-command, and what they are expected to do and how they are expected to be used.

2023-09-20 21:23 UTC, larrydewey commented on README.md
> +- The main function initializes the `env_logger` for logging.
It would be good to explain how to set the environment variable to change the log level at run-time.

2023-09-20 21:23 UTC, larrydewey commented on README.md
> +![alt text](https://github.com/virtee/snpguest/blob/main/docs/regular.png?raw=true)
I cannot see them, either

2023-09-20 21:23 UTC, larrydewey commented on README.md
> +- Several helper functions are defined within the modules to facilitate various tasks, including locating certificates in a directory, comparing certificate values, and verifying attestation report s
I agree

2023-09-21 00:24 UTC, tylerfanelli commented on README.md
> +- Several helper functions are defined within the modules to facilitate various tasks, including locating certificates in a directory, comparing certificate values, and verifying attestation report s
I agree as well. However, much of the code comments would fit nicely in their respective source code files.

2023-09-21 00:49 UTC, tylerfanelli requested changes
Much of this fits into a README, but a lot could also fit into a man page. Code-specific descriptions are better left to source code comments.

However, this is very descriptive and thorough about the usage of the tool (a huge plus for those looking to figure out how the tools works).

Great diagrams as well!

2023-09-21 00:49 UTC, tylerfanelli commented on README.md
> +**SNPguest** is a Command Line Interface utility for managing the AMD SEV-SNP guest environment. This tool allows users to interact with the AMD SEV-SNP guest firmware device enabling various operati
```suggestion
**SNPguest** is a Command Line Interface utility for managing the AMD SEV-SNP guest environment. This tool allows users to interact with the AMD SEV-SNP guest firmware device enabling various operations related to attestation, certificate management, key fetching, and more.
```

I don't think there is any key generation in this tool, moreso fetching keys from the KDS that already exist.

2023-09-21 00:49 UTC, tylerfanelli commented on README.md
> +- It defines a structure for managing certificate paths (`CertPaths`) and functions for obtaining extended certificates from the AMD PSP.
Just for my reference, what's the difference between the two? I usually use them interchangeably. Or is this change because some users may not know what PSP stands for?

2023-09-21 00:49 UTC, tylerfanelli commented on README.md
> +- It contains subcommands for displaying attestation reports and derived keys.
Right, the [sevctl README](https://github.com/virtee/sevctl/blob/main/README.md) does just this, and can be used for reference.

2023-09-21 00:49 UTC, tylerfanelli commented on README.md
> +- Several helper functions are defined within the modules to facilitate various tasks, including locating certificates in a directory, comparing certificate values, and verifying attestation report s
Much of this would also be useful in a man page as well.

2023-09-21 00:49 UTC, tylerfanelli commented on README.md
> +- `-r, --random`: Generate 64 random bytes of data for the report request.
```suggestion
- `-r, --random`: Generate 64 random bytes of data for the report request. (Not used in Hyper-V)
```

2023-09-21 00:49 UTC, tylerfanelli commented on README.md
> +Requests an attestation report from the host and writes it to a file with the provided request data and VMPL. The attestation report is written in binary format to the specified report path. The user
```suggestion
Requests an attestation report from the host and writes it to a file with the provided request data and VMPL. The attestation report is written in binary format to the specified report path. The user can pass 64 bytes of data in any file format into `$REQUEST_FILE` to request the attestation report. The `--random` flag can be used to generate and use random data for the request.

For Microsoft Hyper-V guests, the `--platform` flag is required to use pre-generated request data. The data already generated from the hypervisor will be written into the file provided in `$REQUEST_FILE`. `VMPL` is an optional parameter that defaults to 1. `--random` is not available in Hyper-V, as the request data is pre-generated.
```

2023-09-21 00:49 UTC, tylerfanelli commented on README.md
> +snpguest verify attestation $CERTS_DIR $ATT_REPORT_PATH [-t, --tcb] [-s, --signature]
Why is `[-s, --signature]` an option? Shouldn't the signature be a part of the attestation report?

@DGonzalezVillal @larrydewey as in, must there be a separate flag for the signature?

2023-10-03 20:20 UTC, DGonzalezVillal commented on README.md
> +snpguest verify attestation $CERTS_DIR $ATT_REPORT_PATH [-t, --tcb] [-s, --signature]
Hey, this allows you to perform attestation on only the signature part or only the tcb part.

2023-11-03 19:38 UTC, DGonzalezVillal requested changes
It's still very disorganized and a lot of unnecessary information for a README. I would go back and see other README examples in the repository. I would recommend to remove the summary and file structure sections. A lot of that information I would put as source code documentation in the form of comments. Then the commands section needs restructuring, refer to my comments to see what I mean. You have 2 example sections, one isn't very clear and the other is too wordy. Combine those 2 to show people how to perform both regular & extended attestation in the tool. The building part looks good, you should still mention compiling for hyper-v.

2023-11-03 19:38 UTC, DGonzalezVillal commented on README.md
> +3. **Command Handling**: The `cmd` function is responsible for handling the selected subcommand and performing the corresponding action. It calls either the `cert_authority::fetch_ca` function or the
Same thing as above. Very good summary, but not part of a README

2023-11-03 19:38 UTC, DGonzalezVillal commented on README.md
> +```
Explain what each step is doing.

2023-11-03 19:38 UTC, DGonzalezVillal commented on README.md
> +#### snpguest guest verify certs
```suggestion
#### snpguest verify certs
```

2023-11-03 19:38 UTC, DGonzalezVillal commented on README.md
> +#### snpguest guest verify attestation
```suggestion
#### snpguest guest attestation
```

2023-11-03 19:38 UTC, DGonzalezVillal commented on README.md
> +---
This should be the first part of the README. The way I would divide would be:
A section for the main command, and then a small explanation of the subcommands. 
For Example:
```
### verify
Command to do different types of verification
#### verify certs

snpguest verify certs $CERTS_DIR


Verifies that the provided certificate chain has been properly signed by each certificate. The user needs to provide a directory where all three certificates (ARK, ASK, and VCEK) are stored. An error will be raised if any of the certificates fail verification.

Options:
- `-h, --help`: Show a help message.

Example usage:
# Verifying Certs
snpguest verify certs ./certs
```

Or something along those lines. Again check SEVCTL README

2023-11-03 19:38 UTC, DGonzalezVillal commented on README.md
> +```
This seems very repetitive to what you have in the previous section. The examples should be way shorter. What I would do is go back to the attestation workflow examples and just explain what you're doing in each step. Maybe then add an example for the derived key.

2023-11-06 15:49 UTC, AdithyaKrishnan commented on README.md
> +`snpguest` is a Command Line Interface utility for managing the AMD SEV-SNP guest environment. This tool allows users to interact with the AMD SEV-SNP guest firmware device enabling various operation
I believe @tylerfanelli had suggested to use the term fetch instead of derivation. Can we come to a consensus?

2023-11-06 16:59 UTC, DGonzalezVillal commented on README.md
> +`snpguest` is a Command Line Interface utility for managing the AMD SEV-SNP guest environment. This tool allows users to interact with the AMD SEV-SNP guest firmware device enabling various operation
Derived key fetching

2023-11-10 16:42 UTC, DGonzalezVillal requested changes
Looks great! Only a few last comments and it should be good!

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +Apart from `help`, there are 6 other subcommands for `snpguest` that have been listed below with their purpose.
```suggestion

```

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +Command to Requests certificates.
```suggestion
Command to Requests certificates from the KDS.
```

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +    Requests the certificate authority chain (ARK & ASK) from the KDS. The user needs to specify the certificate encoding to store the certificates in (PEM or DER). Currently, only PEM and DER encodi
```suggestion
    Requests the certificate authority chain (ARK & ASK) from the KDS. The user needs to specify the certificate encoding to store the certificates in (PEM or DER). Currently, only PEM and DER encodings are supported. Both certificates will be in the same encoding. The user must specify their host processor model. The user also needs to provide the path to the directory where the certificates will be stored. If the certificates already exist in the provided directory, they will be overwritten.
```

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +    - `$PROCESSOR_MODEL` : Specifies the host processor model (Milan or Genoa).
```suggestion
    - `$PROCESSOR_MODEL` : Specifies the host processor model. 
```

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +    Requests the VCEK certificate from the KDS. The user needs to specify the certificate encoding to store the certificate in (PEM or DER). Currently, only PEM and DER encodings are supported. The u
```suggestion
    Requests the VCEK certificate from the KDS. The user needs to specify the certificate encoding to store the certificate in (PEM or DER). Currently, only PEM and DER encodings are supported. The user must specify their host processor model. The user also needs to provide the path to the directory where the VCEK will be stored and the path to a stored attestation report that will be used to request the VCEK. If the certificate already exists in the provided directory, it will be overwritten.
```

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +    - `$PROCESSOR_MODEL` : Specifies the host processor model (Milan or Genoa).
```suggestion
    - `$PROCESSOR_MODEL` : Specifies the host processor model. 
```

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +Creates the derived key based on input parameters and stores it. `$KEY_PATH` is the path to store the derived key. `$ROOT_KEY_SELECT` is the root key from which to derive the key (either "vcek" or "v
On guest field select explanation, instead of showing example, just explain what each bit is. User can see example underneath.

2023-11-10 16:42 UTC, DGonzalezVillal commented on README.md
> +Options
Missing platform flag

2023-11-13 15:29 UTC, larrydewey requested changes
Just a couple minor adjustments. With these, i will approve it.

2023-11-13 15:29 UTC, larrydewey commented on README.md
> +- `-p, --platform` : Use platform provided 64 bytes of data for the request report.
```suggestion
- `-p, --platform` : Use platform provided 64 bytes of data for the request report (only available for Hyper-V).
```

2023-11-13 15:29 UTC, larrydewey commented on README.md
> +- `-r, --random`: Generate 64 random bytes of data for the report request. (Not used in Hyper-V)
```suggestion
- `-r, --random`: Generate 64 random bytes of data for the report request (not available for Hyper-V).
```

2023-11-13 15:29 UTC, larrydewey commented on docs/snpguest.1.adoc
> +    -p, --platform Use platform generated 64 bytes of data to pass for the report request
```suggestion
    -p, --platform Use platform generated 64 bytes of data to pass for the report request (only available for Hyper-V)
```

2023-11-13 15:29 UTC, larrydewey commented on docs/snpguest.1.adoc
>      -r, --random  Generate 64 random bytes of data to pass for the report request
```suggestion
    -r, --random  Generate 64 random bytes of data to pass for the report request (not available for Hyper-V)
```

2023-11-13 15:29 UTC, larrydewey commented on src/certs.rs
> +//This file contains code related to managing certificates. It defines a structure for managing certificate paths (`CertPaths`) and functions for obtaining extended certificates from the AMD Secure P
```suggestion
// This file contains code related to managing certificates. It defines a structure for managing certificate paths (`CertPaths`) and functions for obtaining extended certificates from the AMD Secure Processor.
```

2023-11-13 15:29 UTC, larrydewey commented on src/key.rs
> +// - This file contains code for fetching derived keys from root keys. It also includes functions for requesting and saving derived keys.
```suggestion
// This file contains code for fetching derived keys from root keys. It also includes functions for requesting and saving derived keys.
```

2023-11-13 15:40 UTC, larrydewey approved these changes
LGTM!

2023-11-13 16:39 UTC, DGonzalezVillal approved these changes
Awesome, looks great to me. Good job @AdithyaKrishnan

2023-11-13 16:46 UTC, merged