VLEK: Adding VLEK support to tooling
virtee/snpguest pull request #40
Opened 2024-02-15 19:51 UTC by larrydewey

2024-02-15 19:52 UTC, larrydewey commented
Dependent on VLEK support being present in the library (next version)

2024-02-15 23:54 UTC, DGonzalezVillal reviewed
Just a couple of discussion points

2024-02-15 23:54 UTC, DGonzalezVillal commented on src/certs.rs
> +        }
Do we want to return an error if certificate is empty?

2024-02-15 23:54 UTC, DGonzalezVillal commented on src/verify.rs
> +                    println!("The VEK was signed by the AMD ASK!");
Do we want to print VLEK and VCEK? Or as long as it is one of those 2 it doesn't matter? Somewhere we would have to tell people that VLEK will be used over VCEK if both are provided

2024-02-15 23:54 UTC, DGonzalezVillal commented on src/verify.rs
> +
Nice!

2024-02-16 15:38 UTC, larrydewey commented on src/verify.rs
> +                    println!("The VEK was signed by the AMD ASK!");
I am glad you brought that up. It is one of the questions I had as well. Do we individually name out VCEK/VLEK, or do we mention in the documentation that VLEK is used over VCEK? I mean, we have the logic to behave that way anyway, so I think the documentation is needed regardless, but I am open to different wordings here.

2024-02-16 15:39 UTC, larrydewey commented on src/verify.rs
> +
I am about 85% sure this will work. I am still waiting to hear back internally about the formatting of the subject common name for the VLEK. As long as it falls in-line, I think we are good.

2024-02-16 17:36 UTC, larrydewey commented on src/verify.rs
> +                    println!("The VEK was signed by the AMD ASK!");
Resolved in next commit!

2024-02-20 00:12 UTC, DGonzalezVillal requested changes

2024-02-20 00:12 UTC, DGonzalezVillal commented on src/certs.rs
> +            write_cert(path, &cert.cert_type, &cert.data, args.encoding)?;
function write cert needs to be modified to support vlek

2024-02-20 01:08 UTC, larrydewey commented on src/certs.rs
> +            write_cert(path, &cert.cert_type, &cert.data, args.encoding)?;
I have this added the PR for #37

2024-02-22 20:47 UTC, DGonzalezVillal approved these changes
lgtm

2024-02-22 20:49 UTC, merged