VLEK: Adding ASVK Support
virtee/snpguest pull request #43
Opened 2024-02-29 16:45 UTC by larrydewey

With the release of the VLEK, there is a separate api endpoint for requesting VLEK signing keys which are known as an AMD Signing VLEK Key (ASVK). This adds logic to handle these special use-cases. As the [GHCB](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56421.pdf#page=53) does not offer a unique GUID, assumptive logic must be applied to when the file should be named appropriately ASVK or ASK.

2024-02-29 16:46 UTC, larrydewey commented
CC @fitzthum

2024-02-29 19:34 UTC, fitzthum commented on src/fetch.rs
> +            _ => Err(anyhow::anyhow!("Endorsement type not found!")),
You might be able to use the strum crate to do this automatically

2024-02-29 20:54 UTC, larrydewey commented on src/fetch.rs
> +            _ => Err(anyhow::anyhow!("Endorsement type not found!")),
Unfortunately `structopt` requires an `impl FromStr` for any command-line arguments. We don't really use it for anything else. Does `strum` work with `structopt`?

2024-02-29 22:11 UTC, arvindskumar99 approved these changes

2024-03-01 16:33 UTC, tylerfanelli requested changes

2024-03-01 16:33 UTC, tylerfanelli commented on src/fetch.rs
> +            "{KDS_CERT_SITE}{endorser}/v1/{}/{KDS_CERT_CHAIN}",
Shouldn't this be:

```suggestion
            "{KDS_CERT_SITE}/{endorser}/v1/{}/{KDS_CERT_CHAIN}",
```

2024-03-04 15:03 UTC, larrydewey commented on src/fetch.rs
> +            "{KDS_CERT_SITE}{endorser}/v1/{}/{KDS_CERT_CHAIN}",
Nice catch!

2024-03-04 16:55 UTC, tylerfanelli approved these changes

2024-03-04 18:52 UTC, merged