Adding snpguest ok
virtee/snpguest pull request #47
Opened 2024-03-07 21:11 UTC by arvindskumar99

Adding tests to make sure SEV, SEV-ES, and SNP are enabled in guest.

![image](https://github.com/virtee/snpguest/assets/158101868/51424889-2f0f-4571-9162-1c560385445c)

2024-03-08 16:30 UTC, tylerfanelli requested changes
For each test, `[ PASS ]` should tell you everything you need to know regarding the test unless there is some extra parameters to print.

With `[ PASS ] SEV: SEV is enabled`, the `SEV is enabled` part is irrelevant.

2024-03-08 16:31 UTC, larrydewey requested changes

2024-03-08 16:31 UTC, larrydewey commented on src/ok.rs
> +    let temp_bitfield = match get_values(0xC0010131, 0) {
There are a number of additional fields which might be good to bubble up to the user. Particularly, I am thinking of things like DebugSwap_Enabled, VMSARegProt_enabled, SmtProtection_Enabled, etc, which impact the VMSA.

2024-03-08 16:32 UTC, larrydewey commented on src/ok.rs
> +    let temp_bitfield = match get_values(0xC0010131, 0) {
If possible, I think it would be good to cover all of the existing cases.

2024-03-08 18:07 UTC, DGonzalezVillal requested changes
I think some of the logic can be more concise and effective, but you're on the right track!

2024-03-08 18:07 UTC, DGonzalezVillal commented on src/ok.rs
> +    let temp_bitfield = match get_values(0xC0010131, 0) {
Some of these values, if disabled, shouldn't lead to an overall test fail, right @larrydewey? I think the only fail case scenarios should be if any of the guest features (SEV, SEV-ES, SEV-SNP) are disabled, the other tests should only be more of an info-dump. @arvindskumar99 you could maybe pass a Pass TestState for these other features, even if they are disabled.

2024-03-08 18:07 UTC, DGonzalezVillal commented on src/ok.rs
> +enum GuestLevels {
```suggestion
enum GuestFeatures {
```

2024-03-08 18:28 UTC, tylerfanelli commented on src/ok.rs
> +        }
There may be some off chances in which this tool is used incorrectly that `unreachable `will in-fact be reached.. in that case I think err'ing out and printing an error message is useful.

2024-03-08 18:30 UTC, tylerfanelli commented on src/ok.rs
> +}
This tool checks if you're in an SNP guest, which is different then checking if SEV, SEV-ES, and SEV-SNP are available? If SEV-SNP is available, then we know the others are. Why check for all three?

2024-03-08 19:02 UTC, DGonzalezVillal commented
@arvindskumar99 please also modify the README and the docs

2024-03-08 19:32 UTC, arvindskumar99 commented
> @arvindskumar99 please also modify the README and the docs

Sounds good, I'll get started on those changes

2024-03-08 20:28 UTC, larrydewey commented on src/ok.rs
> +    let temp_bitfield = match get_values(0xC0010131, 0) {
Correct. Those should be more of an enabled/disabled state.

2024-03-08 20:31 UTC, larrydewey commented on src/ok.rs
> +}
@tylerfanelli this MSR is a guest protected register by the ASP, so it is good to make sure all three are properly set to being enabled before the guest continues. A guest may be launched in SEV-ES mode, and the guest-owner may think they are in an SEV-SNP enabled machine. This will say yes or no. I don't know that this is a SUPER important thing to verify SEV and SEV-ES are enabled, but it is good transparency.

2024-03-08 20:37 UTC, DGonzalezVillal commented on src/ok.rs
> +}
maybe a flag to test for a specific SEV gen (SEV, ES or SNP)? And test the the previous generations for the generation your testing. So if ES, then do SEV and ES. If SNP then SEV, ES and SNP. That could allow people to test for enablement in their guests for every gen.

2024-03-08 20:38 UTC, tylerfanelli commented on src/ok.rs
> +}
Understood, then this makes sense. Thanks for clearing that up.

2024-03-13 20:25 UTC, arvindskumar99 commented
Made the suggested changes, here's how the results look now.

![image](https://github.com/virtee/snpguest/assets/158101868/8896cdc2-6996-4b02-9143-abc87ad96370)

2024-03-15 16:06 UTC, DGonzalezVillal commented on src/ok.rs
> +}
You have this one huge function where you are essentially doing the same thing for each individual bit. And then calling it 17 times. Can you think of a way of improving the logic and make the code more efficient? You shouldn't need to check the MSR 17 times and you shouldn't need to write and individual  match statement for each guest feature. There is a quicker way to do this!

2024-03-26 18:32 UTC, larrydewey requested changes

2024-03-26 18:32 UTC, larrydewey commented on Cargo.toml
> +closure = "0.3.0"
What are we adding this for?

2024-03-26 18:32 UTC, larrydewey commented on src/ok.rs
> +}
Where this is literally only being used for string values, I don't know if we need it. It might make more sense to just print out the values in the test results.

2024-03-26 18:32 UTC, larrydewey commented on src/ok.rs
> +}
Where we are only modifying two spaces here, it would probably make more sense to do something like:

```rust
    let mut stat = TestState::Fail;
    let mut mesg = "DISABLED".to_string();
    
    if check_bit == 1 {
        stat = TestState::Pass;
        mesg = "ENABLED".to_string();
    } else if optional_field {
        stat = TestState::Pass;
    }
    
    TestResult {
        name: format!("{}", sev_feature),
        stat: stat,
        mesg: Some(mesg)
    }
```

2024-03-26 21:39 UTC, larrydewey approved these changes

2024-03-27 02:40 UTC, tylerfanelli approved these changes

2024-03-28 12:46 UTC, merged